# This specifies when the pipeline should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Stage
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/

  # Test Stage
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Code Quality Checks
        run: ./gradlew check

  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Deploy to Staging Environment
        env:
          DEPLOY_ENV: 'staging'
        run: |
          echo "Deploying application to $DEPLOY_ENV environment..."
          # Add your deployment script/commands here
          # Example: scp or rsync to a remote server
